/**
 * Rows for the tool and build scenarios of batch A (`a-tool-build.json`), beside the shared
 * ones. Written once from the anchors of `spikes/vocabulary/VOCABULARY.md`, before any test
 * ran, and not tuned afterwards. The shared `blade`, `stone`, `rope` and `oak` are reused.
 */
import type { Extra } from "./elements.ts";

export const EXTRA: Extra = {
  elements: [
    {
      id: "round",
      name: "a sawn round of oak",
      kind: "material",
      forms: ["grained", "round"],
      props: { mass: 3, size: 2, hardness: 3, toughness: 4, flammability: 2, absorbency: 2 },
      burnsTo: "ash",
    },
    {
      id: "wedge",
      name: "an iron splitting wedge",
      kind: "thing",
      forms: ["edged", "pointed"],
      props: {
        mass: 2,
        size: 1,
        hardness: 4,
        toughness: 4,
        conductivity: 5,
        meltsAt: 1,
        corrodibility: 5,
      },
    },
    {
      id: "maul",
      name: "a wooden maul",
      kind: "thing",
      forms: ["long", "round", "grained"],
      props: { mass: 3, size: 2, hardness: 3, toughness: 4, flammability: 2, absorbency: 2 },
    },
    {
      id: "mallet",
      name: "a wooden mallet",
      kind: "thing",
      forms: ["long", "grained"],
      props: { mass: 2, size: 1, hardness: 3, toughness: 4, flammability: 2, absorbency: 2 },
    },
    {
      id: "birch",
      name: "birch",
      kind: "plant",
      forms: ["grained", "long"],
      props: { mass: 4, size: 4, hardness: 3, toughness: 4, flammability: 3, absorbency: 2 },
      burnsTo: "ash",
    },
    {
      id: "teeth",
      name: "gnawing teeth",
      kind: "thing",
      forms: ["edged"],
      props: { mass: 0, size: 0, hardness: 4, toughness: 3 },
    },
    {
      id: "rockface",
      name: "a quarry face",
      kind: "thing",
      forms: ["flat"],
      props: { mass: 5, size: 5, hardness: 4, toughness: 1 },
    },
    {
      id: "hammer",
      name: "a stone-headed hammer",
      kind: "thing",
      forms: ["long"],
      props: { mass: 3, size: 2, hardness: 4, toughness: 1 },
    },
    {
      id: "greenwood",
      name: "a green willow branch",
      kind: "plant",
      forms: ["grained", "long"],
      props: {
        mass: 1,
        size: 1,
        hardness: 2,
        toughness: 5,
        flexibility: 3,
        flammability: 1,
        absorbency: 1,
      },
    },
    {
      id: "peg",
      name: "a wooden peg",
      kind: "thing",
      forms: ["grained", "long", "pointed"],
      props: { mass: 1, size: 1, hardness: 2, toughness: 3, flammability: 3, absorbency: 2 },
    },
    {
      id: "trunk",
      name: "a young felled trunk",
      kind: "plant",
      forms: ["grained", "long", "round"],
      props: { mass: 3, size: 4, hardness: 3, toughness: 4, flammability: 2, absorbency: 2 },
    },
    {
      id: "walker",
      name: "a grown person, as a weight",
      kind: "person",
      forms: [],
      props: { mass: 3, size: 3, hardness: 1, toughness: 2 },
    },
    {
      id: "cart",
      name: "a laden cart",
      kind: "thing",
      forms: ["hollow"],
      props: { mass: 5, size: 4, hardness: 3, toughness: 3 },
    },
    {
      id: "rawhide",
      name: "rawhide cord",
      kind: "material",
      forms: ["cord"],
      props: {
        mass: 0,
        size: 1,
        hardness: 1,
        toughness: 5,
        flexibility: 4,
        flammability: 2,
        absorbency: 4,
        perishability: 2,
        swell: 2,
      },
    },
    {
      id: "pole",
      name: "a cut pole or bough",
      kind: "thing",
      forms: ["grained", "long"],
      props: { mass: 2, size: 3, hardness: 2, toughness: 3, flammability: 3, absorbency: 2 },
    },
    {
      id: "cord",
      name: "thin twisted cord",
      kind: "thing",
      forms: ["cord"],
      props: {
        mass: 0,
        size: 1,
        hardness: 1,
        toughness: 4,
        flexibility: 5,
        flammability: 3,
        absorbency: 4,
      },
    },
    {
      id: "sapling",
      name: "a springy sapling",
      kind: "plant",
      forms: ["grained", "long"],
      props: { mass: 2, size: 3, hardness: 2, toughness: 5, flexibility: 3, absorbency: 1 },
    },
    {
      id: "snow",
      name: "fallen snow",
      kind: "material",
      forms: ["granular"],
      props: { mass: 1, size: 2, hardness: 0, toughness: 0, conductivity: 1, meltsAt: 5 },
    },
  ],
  places: [],
};
