// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import ArchiveThroughReducer from "../archive_through_reducer.ts";
import CommandReducer from "../command_reducer.ts";
import JoinReducer from "../join_reducer.ts";
import RegisterArchiverReducer from "../register_archiver_reducer.ts";

export type ArchiveThroughParams = __Infer<typeof ArchiveThroughReducer>;
export type CommandParams = __Infer<typeof CommandReducer>;
export type JoinParams = __Infer<typeof JoinReducer>;
export type RegisterArchiverParams = __Infer<typeof RegisterArchiverReducer>;

