/**
 * pnpm demo                 play the fixed script against live Jev; write the transcript and costs
 * pnpm demo --record        also record every judge answer by request id, for the offline tests
 * pnpm demo --script=FILE   one input per line instead of the built-in script
 * pnpm demo --out=DIR       where to write (default: demo/)
 * pnpm demo --verbose       print the judge's answers as they arrive
 */
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { serializeLog } from "@rpg-jev/core";
import { clockWords, DEMO_SCRIPT } from "@rpg-jev/inn";
import { percentile, USD_PER_INPUT_TOKEN } from "@rpg-jev/jev";
import { flag, openSession, option, ROOT } from "./session.ts";

const scriptFile = option("script");
const inputs = scriptFile
  ? readFileSync(scriptFile, "utf8")
      .split("\n")
      .map((l) => l.trim())
      .filter((l) => l !== "" && !l.startsWith("#"))
  : DEMO_SCRIPT;
const seed = Number(option("seed") ?? 1);
const out = option("out") ?? join(ROOT, "demo");

const session = openSession({
  seed,
  savePath: null,
  fresh: true,
  offline: flag("offline"),
  record: true,
});
const { game, meter } = session;

const traced = option("trace");
if (traced)
  game.trace = (slice, answers) => {
    if (slice.schema === traced)
      console.log(
        `--- ${slice.schema} slice\n${JSON.stringify(slice.state, null, 1)}\n${JSON.stringify(answers)}`,
      );
  };

const transcript: string[] = [
  "# Demo transcript",
  "",
  `Seed ${seed}, ${session.live ? "live `jev-1.13.0`" : "judge offline"}, ${inputs.length} scripted inputs. Generated by \`pnpm demo\`.`,
  "",
  "```text",
  ...game.intro(),
  "",
];
let seen = 0;
for (const text of inputs) {
  if (game.over) break;
  meter.begin(text);
  const started = performance.now();
  const lines = await game.turn(text);
  const wall = Math.round(performance.now() - started);
  const c = meter.current;
  transcript.push(`> ${text}`, "", ...lines, "");
  transcript.push(
    `    [${clockWords(game.world.clock)} | ${c.calls} calls, ${c.questions} questions, ${c.inputTokens} tokens, ${c.latencyMs} ms judge, ${wall} ms wall, $${c.usd.toFixed(5)}${c.fallbacks ? `, ${c.fallbacks} fallbacks` : ""}]`,
    "",
  );
  console.log(`> ${text}\n${lines.join("\n")}\n`);
  if (flag("verbose"))
    for (const e of game.log.slice(seen))
      if (e.kind === "decision") console.log(`   ${e.source} ${JSON.stringify(e.answers)}`);
  seen = game.log.length;
}
transcript.push("```", "");

const actions = meter.actions;
const total = meter.totals();
const judged = actions.filter((a) => a.calls > 0);
const perAction = (n: number) => (actions.length > 0 ? n / actions.length : 0);
const wallLatencies = judged.map((a) => a.latencyMs);
const metrics = {
  seed,
  live: session.live,
  actions: actions.length,
  actionsThatCalledTheJudge: judged.length,
  calls: total.calls,
  questions: total.questions,
  inputTokens: total.inputTokens,
  usd: total.usd,
  fallbacks: total.fallbacks,
  cached: total.cached,
  perAction: {
    calls: perAction(total.calls),
    inputTokens: perAction(total.inputTokens),
    usd: perAction(total.usd),
    judgeLatencyMsMedian: percentile(wallLatencies, 50),
    judgeLatencyMsP90: percentile(wallLatencies, 90),
    judgeLatencyMsWorst: Math.max(0, ...wallLatencies),
  },
  perCall: {
    latencyMsMedian: percentile(meter.callLatencies, 50),
    latencyMsP90: percentile(meter.callLatencies, 90),
    latencyMsP99: percentile(meter.callLatencies, 99),
    inputTokensMean: total.calls > 0 ? total.inputTokens / total.calls : 0,
  },
  /** At one action every ten seconds, which is brisk for a text game. */
  perPlayerHour: {
    actions: 360,
    usd: perAction(total.usd) * 360,
    inputTokens: Math.round(perAction(total.inputTokens) * 360),
  },
  usdPerInputToken: USD_PER_INPUT_TOKEN,
  endedAt: clockWords(game.world.clock),
  quest: game.world.machines.quest?.node,
  byAction: actions,
};

transcript.push(
  "## Cost",
  "",
  `${actions.length} actions, ${total.calls} judge calls, ${total.inputTokens} input tokens, $${total.usd.toFixed(4)} in all.`,
  `Per action: ${metrics.perAction.calls.toFixed(2)} calls, ${Math.round(metrics.perAction.inputTokens)} tokens, $${metrics.perAction.usd.toFixed(6)}.`,
  `Judge latency per action that called it: median ${metrics.perAction.judgeLatencyMsMedian} ms, p90 ${metrics.perAction.judgeLatencyMsP90} ms, worst ${metrics.perAction.judgeLatencyMsWorst} ms.`,
  `Per call: median ${metrics.perCall.latencyMsMedian} ms, p99 ${metrics.perCall.latencyMsP99} ms, ${Math.round(metrics.perCall.inputTokensMean)} tokens.`,
  `At 360 actions an hour: $${metrics.perPlayerHour.usd.toFixed(4)} per player-hour.`,
  "",
);

mkdirSync(out, { recursive: true });
writeFileSync(join(out, "transcript.md"), transcript.join("\n"));
writeFileSync(join(out, "metrics.json"), `${JSON.stringify(metrics, null, 2)}\n`);
writeFileSync(join(out, "log.jsonl"), `${serializeLog(game.log)}\n`);
if (flag("record") && session.recorder) {
  const file = { seed, inputs, recordings: session.recorder.recordings };
  writeFileSync(join(out, "recordings.json"), `${JSON.stringify(file)}\n`);
}
console.log(
  `\n${actions.length} actions, ${total.calls} calls, ${total.inputTokens} tokens, $${total.usd.toFixed(4)}. Quest: ${metrics.quest}. Wrote ${out}`,
);
