// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  slot: __t.u32().primaryKey(),
  tick: __t.u32(),
  mode: __t.string(),
  things: __t.u32(),
  scoringMicros: __t.u32().name("scoring_micros"),
  tickMicros: __t.u32().name("tick_micros"),
  fallback: __t.string(),
  agreed: __t.u32(),
  draws: __t.u32(),
  scored: __t.u32(),
  cached: __t.u32(),
});
