// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const Event = __t.object("Event", {
  seq: __t.u64(),
  reader: __t.identity(),
  generation: __t.string(),
  payload: __t.string(),
});
export type Event = __Infer<typeof Event>;

export const JepaConfig = __t.object("JepaConfig", {
  id: __t.u8(),
  mode: __t.string(),
  tickMicros: __t.u64(),
});
export type JepaConfig = __Infer<typeof JepaConfig>;

export const JepaTick = __t.object("JepaTick", {
  slot: __t.u32(),
  tick: __t.u32(),
  mode: __t.string(),
  things: __t.u32(),
  scoringMicros: __t.u32(),
  tickMicros: __t.u32(),
  fallback: __t.string(),
  agreed: __t.u32(),
  draws: __t.u32(),
  scored: __t.u32(),
  cached: __t.u32(),
});
export type JepaTick = __Infer<typeof JepaTick>;

export const Player = __t.object("Player", {
  identity: __t.identity(),
  actor: __t.string(),
  seq: __t.u32(),
  command: __t.string(),
  ok: __t.bool(),
  reason: __t.string(),
  lastMicros: __t.i64(),
  lastRevision: __t.u32(),
  viewUntilMicros: __t.i64(),
});
export type Player = __Infer<typeof Player>;

export const Timer = __t.object("Timer", {
  id: __t.u64(),
  scheduledAt: __t.scheduleAt(),
});
export type Timer = __Infer<typeof Timer>;

export const Viewer = __t.object("Viewer", {
  identity: __t.identity(),
  json: __t.string(),
  seq: __t.u32(),
  ok: __t.bool(),
  reason: __t.string(),
  command: __t.string(),
});
export type Viewer = __Infer<typeof Viewer>;

export const WorldState = __t.object("WorldState", {
  id: __t.u8(),
  json: __t.string(),
  revision: __t.u32(),
  generation: __t.string(),
  owner: __t.identity(),
  archiver: __t.identity(),
  archived: __t.u64(),
});
export type WorldState = __Infer<typeof WorldState>;

